development: &default
  adapter: postgresql
  host: localhost
  database: hoard_development

production:
  <<: *default
  database: hoard_production
  pool: 10

test:
  <<: *default
  database: hoard_test
  min_messages: warning
